import { useEffect, useRef, useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { ActionButton, Card, SectionTitle, StatusPill, palette } from '@/components/ui';
import { barcodeDetectorStatus, detectEanFromImage } from '@/features/foods/barcode-detector.web';
import { processFoodLabelPhoto } from '@/features/foods/food-photo-processing.web';
import type { Food, FoodBaseUnit, FoodDataOrigin, FoodDraft, FoodPhotoDraft } from '@/mvp/food-types';
import { macroEnergy } from '@/mvp/nutrition-calculations';
import { foodRepository } from '@/storage/food-repository.web';

const EMPTY: FoodDraft = { name: '', brand: '', supermarket: '', barcode: null, baseUnit: 'g', energyKcal: 0, energyKj: null, proteinG: 0, carbohydratesG: 0, fatG: 0, energySource: 'declared', dataOrigin: 'manual', notes: '', favorite: false };

export function FoodCatalog() {
  const [foods, setFoods] = useState<Food[]>([]); const [draft, setDraft] = useState<FoodDraft>(EMPTY); const [editingId, setEditingId] = useState<string | undefined>();
  const [portionName, setPortionName] = useState(''); const [portionAmount, setPortionAmount] = useState(0); const [photo, setPhoto] = useState<FoodPhotoDraft>();
  const [search, setSearch] = useState(''); const [favorites, setFavorites] = useState(false); const [recent, setRecent] = useState(false); const [showForm, setShowForm] = useState(false);
  const [detector, setDetector] = useState<{ available: boolean; reason: string | null }>({ available: false, reason: 'Comprobando lector local…' });
  const [message, setMessage] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const photoInput = useRef<HTMLInputElement>(null); const scanInput = useRef<HTMLInputElement>(null);
  async function refresh() { setFoods(await foodRepository.list({ search, favorites, recent })); }
  useEffect(() => { void refresh(); }, [search, favorites, recent]);
  useEffect(() => { void barcodeDetectorStatus().then((status) => setDetector({ available: status.available, reason: status.reason })); }, []);
  const set = <K extends keyof FoodDraft>(key: K, value: FoodDraft[K]) => setDraft({ ...draft, [key]: value });
  async function run(success: string, operation: () => Promise<void>) { setBusy(true); setError(null); try { await operation(); await refresh(); setMessage(success); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado.'); } finally { setBusy(false); } }
  function reset() { setDraft(EMPTY); setEditingId(undefined); setPortionName(''); setPortionAmount(0); setPhoto(undefined); setShowForm(false); }
  function edit(food: Food) { setDraft({ name: food.name, brand: food.brand, supermarket: food.supermarket, barcode: food.barcode, baseUnit: food.baseUnit, energyKcal: food.energyKcal, energyKj: food.energyKj, proteinG: food.proteinG, carbohydratesG: food.carbohydratesG, fatG: food.fatG, energySource: food.energySource, dataOrigin: food.dataOrigin, notes: food.notes, favorite: food.favorite }); setEditingId(food.id); setShowForm(true); }
  return <View style={{ gap: 16 }}>
    {error ? <Notice danger text={error}/> : message ? <Notice text={message}/> : null}
    <Card><SectionTitle eyebrow="Catálogo local">Alimentos</SectionTitle><TextInput accessibilityLabel="Buscar alimentos" placeholder="Buscar nombre, marca, supermercado o EAN" value={search} onChangeText={setSearch} style={input}/><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Filter label="Favoritos" active={favorites} onPress={() => setFavorites(!favorites)}/><Filter label="Recientes" active={recent} onPress={() => setRecent(!recent)}/></View><ActionButton label="Añadir alimento" onPress={() => { reset(); setShowForm(true); }}/></Card>
    {showForm ? <Card><SectionTitle eyebrow={editingId ? 'Edición' : 'Nuevo'}>{editingId ? 'Editar alimento' : 'Añadir alimento'}</SectionTitle>
      <Field label="Nombre" value={draft.name} onChange={(v) => set('name', v)}/><Field label="Marca (opcional)" value={draft.brand} onChange={(v) => set('brand', v)}/><Field label="Supermercado (opcional)" value={draft.supermarket} onChange={(v) => set('supermarket', v)}/><Field label="EAN-13 o EAN-8 (opcional)" value={draft.barcode ?? ''} onChange={(v) => { set('barcode', v || null); set('dataOrigin', v ? 'barcode-manual' : 'manual'); }}/>
      <View style={{ backgroundColor: detector.available ? '#eef8f3' : palette.warningBackground, borderRadius: 14, padding: 12, gap: 8 }}><Text selectable style={{ color: detector.available ? palette.greenDark : palette.warning, fontWeight: '700' }}>{detector.available ? 'Lector EAN local disponible en este navegador.' : detector.reason}</Text><ActionButton tone="secondary" label="Fotografiar código EAN" disabled={!detector.available || busy} onPress={() => scanInput.current?.click()}/><div style={{ display: 'none' }}><input ref={scanInput} aria-label="Fotografiar código EAN" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void run('Código EAN detectado localmente.', async () => { const code = await detectEanFromImage(file); setDraft((current) => ({ ...current, barcode: code, dataOrigin: 'barcode-scanned' })); }); event.currentTarget.value = ''; }}/></div></View>
      <Choice label="Referencia nutricional" values={[["g","Por 100 g"],["ml","Por 100 ml"]]} selected={draft.baseUnit} onSelect={(v) => set('baseUnit', v as FoodBaseUnit)}/>
      <NumberField label="Energía (kcal)" value={draft.energyKcal} onChange={(v) => set('energyKcal', v)}/><NumberField label="Energía (kJ, opcional)" value={draft.energyKj ?? 0} onChange={(v) => set('energyKj', v || null)}/><NumberField label="Proteínas (g)" value={draft.proteinG} onChange={(v) => set('proteinG', v)}/><NumberField label="Carbohidratos (g)" value={draft.carbohydratesG} onChange={(v) => set('carbohydratesG', v)}/><NumberField label="Grasas (g)" value={draft.fatG} onChange={(v) => set('fatG', v)}/>
      <Text selectable style={{ color: palette.muted }}>4/4/9 calcula {Math.round(macroEnergy(draft.proteinG, draft.carbohydratesG, draft.fatG))} kcal. La energía declarada prevalece.</Text>
      <Field label="Nombre de porción (opcional)" value={portionName} onChange={setPortionName}/><NumberField label={`Cantidad de la porción (${draft.baseUnit})`} value={portionAmount} onChange={setPortionAmount}/><Field label="Notas (opcional)" value={draft.notes} onChange={(v) => set('notes', v)}/>
      <ActionButton tone="secondary" label={photo ? `Fotografía preparada · ${(photo.size / 1024).toFixed(0)} KB` : 'Fotografiar o seleccionar etiqueta'} onPress={() => photoInput.current?.click()}/><div style={{ display: 'none' }}><input ref={photoInput} aria-label="Fotografía local de etiqueta" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void run('Fotografía recodificada localmente.', async () => { const processed = await processFoodLabelPhoto(file); setPhoto(processed); setDraft((current) => ({ ...current, dataOrigin: 'label-photo' })); }); event.currentTarget.value = ''; }}/></div>
      <ActionButton label="Guardar alimento" disabled={busy} onPress={() => void run('Alimento guardado localmente.', async () => { await foodRepository.save(draft, portionName ? [{ name: portionName, amount: portionAmount }] : [], photo, editingId); reset(); })}/><ActionButton tone="secondary" label="Cancelar" onPress={reset}/>
    </Card> : null}
    {foods.length === 0 ? <Card><Text selectable style={{ color: palette.muted }}>No hay alimentos que coincidan.</Text></Card> : foods.map((food) => <Card key={food.id}><View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: 10 }}><View style={{ flex: 1 }}><Text selectable style={{ color: palette.ink, fontSize: 18, fontWeight: '800' }}>{food.name}</Text><Text selectable style={{ color: palette.muted }}>{[food.brand, food.supermarket, food.barcode].filter(Boolean).join(' · ') || 'Sin marca'}</Text></View>{food.favorite ? <StatusPill label="Favorito" tone="good"/> : null}</View><Text selectable style={{ color: palette.ink }}>{food.energyKcal} kcal · P {food.proteinG} · C {food.carbohydratesG} · G {food.fatG} por 100 {food.baseUnit}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><ActionButton tone="secondary" label="Editar" onPress={() => edit(food)}/><ActionButton tone="secondary" label={food.favorite ? 'Quitar favorito' : 'Favorito'} onPress={() => void run('Favorito actualizado.', () => foodRepository.setFavorite(food.id, !food.favorite))}/><ActionButton tone="danger" label="Archivar" onPress={() => { if (window.confirm('¿Archivar este alimento? Los consumos históricos no se modificarán.')) void run('Alimento archivado.', () => foodRepository.setArchived(food.id, true)); }}/></View></Card>)}
  </View>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <View style={{ gap: 6 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} style={input}/></View>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <Field label={label} value={String(value)} onChange={(v) => onChange(Number(v.replace(',', '.')) || 0)}/>; }
function Choice({ label, values, selected, onSelect }: { label: string; values: string[][]; selected: string; onSelect: (v: string) => void }) { return <View style={{ gap: 8 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text><View style={{ flexDirection: 'row', gap: 8 }}>{values.map(([value='', text='']) => <Filter key={value} label={text} active={value === selected} onPress={() => onSelect(value)}/>)}</View></View>; }
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={{ borderWidth: 1, borderColor: active ? palette.greenDark : palette.border, backgroundColor: active ? palette.mint : '#fff', borderRadius: 12, paddingHorizontal: 13, paddingVertical: 9 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text></Pressable>; }
function Notice({ text, danger = false }: { text: string; danger?: boolean }) { return <View style={{ backgroundColor: danger ? palette.dangerBackground : '#eaf5ff', borderRadius: 14, padding: 12 }}><Text selectable style={{ color: danger ? palette.danger : palette.navySoft, fontWeight: '700' }}>{text}</Text></View>; }
const input = { borderWidth: 1, borderColor: palette.border, borderRadius: 14, padding: 13, color: palette.ink, backgroundColor: '#f9fbfa', fontSize: 16 } as const;
