import { useEffect, useRef, useState } from 'react';
import { Image, Pressable, Text, TextInput, View } from 'react-native';
import { ActionButton, Card, SectionTitle, StatusPill, palette } from '@/components/ui';
import { barcodeDetectorStatus, detectEanFromImage } from '@/features/foods/barcode-detector.web';
import { processFoodLabelPhoto } from '@/features/foods/food-photo-processing.web';
import type { Food, FoodBaseUnit, FoodDraft, FoodPhoto, FoodPhotoDraft } from '@/mvp/food-types';
import { macroEnergy } from '@/mvp/nutrition-calculations';
import { foodRepository, type FoodPortionDraft } from '@/storage/food-repository.web';
import { AccessibleDialog } from '@/components/accessible-dialog.web';

const EMPTY: FoodDraft = { name: '', brand: '', supermarket: '', barcode: null, baseUnit: 'g', energyKcal: 0, energyKj: null, proteinG: 0, carbohydratesG: 0, fatG: 0, energySource: 'declared', dataOrigin: 'manual', notes: '', favorite: false };

export function FoodCatalog() {
  const [foods, setFoods] = useState<Food[]>([]); const [draft, setDraft] = useState<FoodDraft>(EMPTY); const [editingId, setEditingId] = useState<string>();
  const [portions, setPortions] = useState<FoodPortionDraft[]>([]); const [portionName, setPortionName] = useState(''); const [portionAmount, setPortionAmount] = useState(0); const [editingPortion, setEditingPortion] = useState<number | null>(null);
  const [newPhoto, setNewPhoto] = useState<FoodPhotoDraft>(); const [storedPhoto, setStoredPhoto] = useState<FoodPhoto | null>(null); const [removePhoto, setRemovePhoto] = useState(false);
  const [search, setSearch] = useState(''); const [favorites, setFavorites] = useState(false); const [recent, setRecent] = useState(false); const [showForm, setShowForm] = useState(false);
  const [detector, setDetector] = useState({ available: false, reason: 'Comprobando lector local…' as string | null }); const [message, setMessage] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [pendingConfirmation, setPendingConfirmation] = useState<{ title: string; description: string; confirmLabel: string; action: () => void } | null>(null);
  const photoInput = useRef<HTMLInputElement>(null); const scanInput = useRef<HTMLInputElement>(null);
  async function refresh() { setFoods(await foodRepository.list({ search, favorites, recent })); }
  useEffect(() => { void refresh(); }, [search, favorites, recent]);
  useEffect(() => { void barcodeDetectorStatus().then(setDetector); }, []);
  const set = <K extends keyof FoodDraft>(key: K, value: FoodDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  async function run(success: string, operation: () => Promise<void>) { setBusy(true); setError(null); try { await operation(); await refresh(); setMessage(success); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado.'); } finally { setBusy(false); } }
  function reset() { setDraft(EMPTY); setEditingId(undefined); setPortions([]); setPortionName(''); setPortionAmount(0); setEditingPortion(null); setNewPhoto(undefined); setStoredPhoto(null); setRemovePhoto(false); setShowForm(false); }
  async function edit(food: Food) {
    const [savedPortions, savedPhoto] = await Promise.all([foodRepository.portions(food.id), foodRepository.photo(food.id)]);
    setDraft({ name: food.name, brand: food.brand, supermarket: food.supermarket, barcode: food.barcode, baseUnit: food.baseUnit, energyKcal: food.energyKcal, energyKj: food.energyKj, proteinG: food.proteinG, carbohydratesG: food.carbohydratesG, fatG: food.fatG, energySource: food.energySource, dataOrigin: food.dataOrigin, notes: food.notes, favorite: food.favorite });
    setPortions(savedPortions.map(({ id, name, amount }) => ({ id, name, amount }))); setStoredPhoto(savedPhoto ?? null); setEditingId(food.id); setNewPhoto(undefined); setRemovePhoto(false); setShowForm(true);
  }
  function savePortionDraft() { if (!portionName.trim() || portionAmount <= 0) { setError('Introduce nombre y cantidad válidos para la porción.'); return; } const value = { ...(editingPortion === null ? {} : portions[editingPortion]), name: portionName.trim(), amount: portionAmount }; setPortions(editingPortion === null ? [...portions, value] : portions.map((item, index) => index === editingPortion ? value : item)); setPortionName(''); setPortionAmount(0); setEditingPortion(null); }
  const calculatedEnergy = macroEnergy(draft.proteinG, draft.carbohydratesG, draft.fatG);
  return <View style={{ gap: 16 }}>
    {error ? <Notice danger text={error}/> : message ? <Notice text={message}/> : null}
    <Card><SectionTitle eyebrow="Catálogo local">Alimentos</SectionTitle><TextInput accessibilityLabel="Buscar alimentos" placeholder="Buscar nombre, marca, supermercado o EAN" value={search} onChangeText={setSearch} style={input}/><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Filter label="Favoritos" active={favorites} onPress={() => setFavorites(!favorites)}/><Filter label="Recientes" active={recent} onPress={() => setRecent(!recent)}/></View><ActionButton label="Añadir alimento" onPress={() => { reset(); setShowForm(true); }}/></Card>
    {showForm ? <Card><SectionTitle eyebrow={editingId ? 'Edición' : 'Nuevo'}>{editingId ? 'Editar alimento' : 'Añadir alimento'}</SectionTitle>
      <Field label="Nombre" value={draft.name} onChange={(value) => set('name', value)}/><Field label="Marca (opcional)" value={draft.brand} onChange={(value) => set('brand', value)}/><Field label="Supermercado (opcional)" value={draft.supermarket} onChange={(value) => set('supermarket', value)}/><Field label="EAN-13 o EAN-8 (opcional)" value={draft.barcode ?? ''} onChange={(value) => { set('barcode', value || null); set('dataOrigin', value ? 'barcode-manual' : 'manual'); }}/>
      <View style={{ backgroundColor: detector.available ? '#eef8f3' : palette.warningBackground, borderRadius: 14, padding: 12, gap: 8 }}><Text selectable style={{ color: detector.available ? palette.greenDark : palette.warning, fontWeight: '700' }}>{detector.available ? 'Lector EAN local disponible en este navegador.' : detector.reason}</Text><ActionButton tone="secondary" label="Fotografiar código EAN" disabled={!detector.available || busy} onPress={() => scanInput.current?.click()}/><div style={{ display: 'none' }}><input ref={scanInput} aria-label="Fotografiar código EAN" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void run('Código EAN detectado localmente.', async () => { const code = await detectEanFromImage(file); setDraft((current) => ({ ...current, barcode: code, dataOrigin: 'barcode-scanned' })); }); event.currentTarget.value = ''; }}/></div></View>
      <Choice label="Referencia nutricional" values={[["g", "Por 100 g"], ["ml", "Por 100 ml"]]} selected={draft.baseUnit} onSelect={(value) => set('baseUnit', value as FoodBaseUnit)}/>
      <Choice label="Origen de la energía" values={[["declared", "Declarada"], ["calculated", "Calculada 4/4/9"]]} selected={draft.energySource} onSelect={(value) => set('energySource', value as FoodDraft['energySource'])}/>
      {draft.energySource === 'declared' ? <><NumberField label="Energía (kcal)" value={draft.energyKcal} onChange={(value) => set('energyKcal', value)}/><NumberField label="Energía (kJ, opcional)" value={draft.energyKj ?? 0} onChange={(value) => set('energyKj', value || null)}/></> : <View style={{ backgroundColor: '#eef8f3', borderRadius: 14, padding: 12 }}><Text selectable style={{ color: palette.greenDark, fontWeight: '800' }}>Calculada: {calculatedEnergy.toFixed(1)} kcal por 100 {draft.baseUnit}</Text><Text selectable style={{ color: palette.muted }}>Proteínas × 4 + carbohidratos × 4 + grasas × 9. Se guarda con la etiqueta “Calculada”.</Text></View>}
      <NumberField label="Proteínas (g)" value={draft.proteinG} onChange={(value) => set('proteinG', value)}/><NumberField label="Carbohidratos (g)" value={draft.carbohydratesG} onChange={(value) => set('carbohydratesG', value)}/><NumberField label="Grasas (g)" value={draft.fatG} onChange={(value) => set('fatG', value)}/>
      {draft.energySource === 'declared' ? <Text selectable style={{ color: palette.muted }}>Comparación 4/4/9: {calculatedEnergy.toFixed(1)} kcal. Se conserva la energía declarada.</Text> : null}
      <View style={{ borderTopWidth: 1, borderTopColor: palette.border, paddingTop: 12, gap: 9 }}><Text selectable style={{ color: palette.ink, fontWeight: '900' }}>Porciones personalizadas</Text>{portions.map((portion, index) => <View key={portion.id ?? `${portion.name}-${index}`} style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' }}><Text selectable style={{ color: palette.ink, flex: 1 }}>{portion.name} · {portion.amount} {draft.baseUnit}</Text><ActionButton tone="secondary" label={`Editar porción ${portion.name}`} onPress={() => { setPortionName(portion.name); setPortionAmount(portion.amount); setEditingPortion(index); }}/><ActionButton tone="danger" label={`Eliminar porción ${portion.name}`} onPress={() => setPendingConfirmation({ title: 'Eliminar porción', description: `Se quitará “${portion.name}” del formulario. El alimento no cambiará hasta que lo guardes.`, confirmLabel: 'Eliminar porción', action: () => setPortions(portions.filter((_, position) => position !== index)) })}/></View>)}<Field label="Nombre de porción" value={portionName} onChange={setPortionName}/><NumberField label={`Cantidad de la porción (${draft.baseUnit})`} value={portionAmount} onChange={setPortionAmount}/><ActionButton tone="secondary" label={editingPortion === null ? 'Añadir porción' : 'Guardar cambios de porción'} onPress={savePortionDraft}/></View>
      <Field label="Notas (opcional)" value={draft.notes} onChange={(value) => set('notes', value)}/>
      <PhotoPreview blob={newPhoto?.thumbnail ?? (!removePhoto ? storedPhoto?.thumbnail : undefined)} label="Vista previa de la etiqueta"/>
      <ActionButton tone="secondary" label={newPhoto ? `Fotografía preparada · ${(newPhoto.size / 1024).toFixed(0)} KB` : storedPhoto && !removePhoto ? 'Sustituir fotografía' : 'Fotografiar o seleccionar etiqueta'} onPress={() => photoInput.current?.click()}/><div style={{ display: 'none' }}><input ref={photoInput} aria-label="Fotografía local de etiqueta" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void run('Fotografía recodificada localmente.', async () => { const processed = await processFoodLabelPhoto(file); setNewPhoto(processed); setRemovePhoto(false); setDraft((current) => ({ ...current, dataOrigin: 'label-photo' })); }); event.currentTarget.value = ''; }}/></div>
      {(storedPhoto || newPhoto) && !removePhoto ? <ActionButton tone="danger" label="Eliminar fotografía" onPress={() => setPendingConfirmation({ title: 'Eliminar fotografía', description: 'Se quitará la fotografía del formulario sin borrar el alimento. El cambio se aplicará al guardar.', confirmLabel: 'Eliminar fotografía', action: () => { setNewPhoto(undefined); setRemovePhoto(true); } })}/>: null}
      <ActionButton label="Guardar alimento" disabled={busy} onPress={() => void run('Alimento, porciones y fotografía guardados localmente.', async () => { await foodRepository.save(draft, { portions, photo: removePhoto ? null : newPhoto }, editingId); reset(); })}/><ActionButton tone="secondary" label="Cancelar" onPress={reset}/>
    </Card> : null}
    {foods.length === 0 ? <Card><Text selectable style={{ color: palette.muted }}>No hay alimentos que coincidan.</Text></Card> : foods.map((food) => <FoodCard key={food.id} food={food} onEdit={() => void edit(food)} onFavorite={() => void run('Favorito actualizado.', () => foodRepository.setFavorite(food.id, !food.favorite))} onArchive={() => setPendingConfirmation({ title: 'Archivar alimento', description: `${food.name} dejará de aparecer en el catálogo activo. Los consumos históricos conservarán sus datos.`, confirmLabel: 'Archivar alimento', action: () => void run('Alimento archivado.', () => foodRepository.setArchived(food.id, true)) })}/>) }
    <AccessibleDialog confirmLabel={pendingConfirmation?.confirmLabel ?? 'Confirmar'} danger description={pendingConfirmation?.description} onCancel={() => setPendingConfirmation(null)} onConfirm={() => { pendingConfirmation?.action(); setPendingConfirmation(null); }} open={Boolean(pendingConfirmation)} title={pendingConfirmation?.title ?? 'Confirmar acción'}/>
  </View>;
}

function FoodCard({ food, onEdit, onFavorite, onArchive }: { food: Food; onEdit: () => void; onFavorite: () => void; onArchive: () => void }) { const [photo, setPhoto] = useState<FoodPhoto | null>(null); const [portions, setPortions] = useState<FoodPortionDraft[]>([]); useEffect(() => { void Promise.all([foodRepository.photo(food.id), foodRepository.portions(food.id)]).then(([nextPhoto, nextPortions]) => { setPhoto(nextPhoto ?? null); setPortions(nextPortions); }); }, [food.id, food.updatedAt]); return <Card><View style={{ flexDirection: 'row', justifyContent: 'space-between', gap: 10 }}><View style={{ flex: 1 }}><Text selectable style={{ color: palette.ink, fontSize: 18, fontWeight: '800' }}>{food.name}</Text><Text selectable style={{ color: palette.muted }}>{[food.brand, food.supermarket, food.barcode].filter(Boolean).join(' · ') || 'Sin marca'}</Text></View>{food.favorite ? <StatusPill label="Favorito" tone="good"/> : null}</View><PhotoPreview blob={photo?.thumbnail} label={`Fotografía de ${food.name}`}/><Text selectable style={{ color: palette.ink }}>{food.energyKcal.toFixed(1)} kcal · P {food.proteinG} · C {food.carbohydratesG} · G {food.fatG} por 100 {food.baseUnit}</Text><StatusPill label={food.energySource === 'calculated' ? 'Calculada 4/4/9' : 'Declarada'} tone={food.energySource === 'calculated' ? 'warning' : 'neutral'}/>{portions.length ? <Text selectable style={{ color: palette.muted }}>Porciones: {portions.map((portion) => `${portion.name} (${portion.amount} ${food.baseUnit})`).join(' · ')}</Text> : null}<View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><ActionButton tone="secondary" label={`Editar ${food.name}`} onPress={onEdit}/><ActionButton tone="secondary" label={food.favorite ? 'Quitar favorito' : 'Favorito'} onPress={onFavorite}/><ActionButton tone="danger" label={`Archivar ${food.name}`} onPress={onArchive}/></View></Card>; }
function PhotoPreview({ blob, label }: { blob?: Blob; label: string }) { const [url, setUrl] = useState<string | null>(null); useEffect(() => { if (!blob) { setUrl(null); return; } const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]); return url ? <Image accessibilityLabel={label} source={{ uri: url }} style={{ width: '100%', aspectRatio: 16 / 9, borderRadius: 14 }}/> : null; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View style={{ gap: 6 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} style={input}/></View>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label} value={String(value)} onChange={(value) => onChange(Number(value.replace(',', '.')) || 0)}/>; }
function Choice({ label, values, selected, onSelect }: { label: string; values: string[][]; selected: string; onSelect: (value: string) => void }) { return <View style={{ gap: 8 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{values.map(([value = '', text = '']) => <Filter key={value} label={text} active={value === selected} onPress={() => onSelect(value)}/>)}</View></View>; }
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={{ borderWidth: 1, borderColor: active ? palette.greenDark : palette.border, backgroundColor: active ? palette.mint : '#fff', borderRadius: 12, paddingHorizontal: 13, paddingVertical: 9 }}><Text selectable style={{ color: palette.ink, fontWeight: '700' }}>{label}</Text></Pressable>; }
function Notice({ text, danger = false }: { text: string; danger?: boolean }) { return <View style={{ backgroundColor: danger ? palette.dangerBackground : '#eaf5ff', borderRadius: 14, padding: 12 }}><Text selectable style={{ color: danger ? palette.danger : palette.navySoft, fontWeight: '700' }}>{text}</Text></View>; }
const input = { borderWidth: 1, borderColor: palette.border, borderRadius: 14, padding: 13, color: palette.ink, backgroundColor: '#f9fbfa', fontSize: 16 } as const;
