import { useEffect, useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { ActionButton, Card, SectionTitle, palette } from '@/components/ui';
import { dataErasureService, type ErasureSummary } from '@/privacy/data-erasure-service.web';
import type { StorageStatus } from '@/storage/dataset-types';
import { StorageStatusCard } from '@/components/storage-status-card';
import { AccessibleDialog } from '@/components/accessible-dialog.web';

export function SettingsPrivacy({ waterQuickAmounts, dailyStepsGoal, storage, busy, onSaveWater, onSaveStepsGoal, onRequestPersistence, onDeleted }: { waterQuickAmounts: number[]; dailyStepsGoal: number; storage: StorageStatus; busy: boolean; onSaveWater: (values: number[]) => Promise<void>; onSaveStepsGoal: (value: number) => Promise<void>; onRequestPersistence: () => void; onDeleted: () => Promise<void> }) {
  const [waterText, setWaterText] = useState(waterQuickAmounts.join(', ')); const [stepsGoalText, setStepsGoalText] = useState(String(dailyStepsGoal)); const [confirmation, setConfirmation] = useState(''); const [summary, setSummary] = useState<ErasureSummary | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState<string | null>(null); const [eraseReviewOpen, setEraseReviewOpen] = useState(false);
  useEffect(() => { setWaterText(waterQuickAmounts.join(', ')); }, [waterQuickAmounts.join('|')]);
  useEffect(() => { setStepsGoalText(String(dailyStepsGoal)); }, [dailyStepsGoal]);
  useEffect(() => { void dataErasureService.summary().then(setSummary).catch((caught) => setError(messageFor(caught))); }, []);
  async function saveWater() { setError(null); try { const values = waterText.split(/[,;\s]+/).filter(Boolean).map(Number); await onSaveWater(values); setMessage('Accesos rápidos de agua actualizados.'); } catch (caught) { setError(messageFor(caught)); } }
  async function saveStepsGoal() { setError(null); try { await onSaveStepsGoal(Number(stepsGoalText)); setMessage('Objetivo diario de pasos actualizado.'); } catch (caught) { setError(messageFor(caught)); } }
  async function erase() { setError(null); try { await dataErasureService.eraseActiveDataset(confirmation); setEraseReviewOpen(false); setMessage('El dataset activo se ha vaciado. La base 0.1.1, backups y datasets de rollback no se han eliminado.'); await onDeleted(); } catch (caught) { setError(messageFor(caught)); } }
  return <View style={{ gap: 16 }}>{error ? <Notice danger text={error}/> : message ? <Notice text={message}/> : null}<Card><SectionTitle eyebrow="Ajustes">Pasos</SectionTitle><Text selectable style={{ color: palette.muted }}>Define tu objetivo diario manual. El valor inicial es 10.000 pasos; NutrIAsta no lee sensores ni lo interpreta como una recomendación médica.</Text><TextInput accessibilityLabel="Objetivo diario de pasos" inputMode="numeric" value={stepsGoalText} onChangeText={setStepsGoalText} style={input}/><ActionButton label="Guardar objetivo diario de pasos" disabled={busy} onPress={() => void saveStepsGoal()}/></Card><Card><SectionTitle eyebrow="Ajustes">Agua</SectionTitle><Text selectable style={{ color: palette.muted }}>Configura entre 1 y 6 accesos rápidos en ml, separados por comas. Valores iniciales: 250 y 500 ml.</Text><TextInput accessibilityLabel="Accesos rápidos de agua" value={waterText} onChangeText={setWaterText} style={input}/><ActionButton label="Guardar accesos rápidos de agua" disabled={busy} onPress={() => void saveWater()}/></Card><StorageStatusCard status={storage} onRequestPersistence={onRequestPersistence}/><Card><SectionTitle eyebrow="Privacidad">Eliminar todos mis datos</SectionTitle><Text selectable style={{ color: palette.warning, lineHeight: 20, fontWeight: '700' }}>Esta acción elimina las filas funcionales del dataset activo en las 26 tablas. No elimina la base histórica `nutriasta`, el catálogo técnico de datasets, datasets de rollback o recuperación, archivos de backup guardados en Archivos ni la PWA.</Text><Text selectable style={{ color: palette.ink }}>Filas activas detectadas: {summary?.totalRows ?? '…'}.</Text><Text selectable style={{ color: palette.ink }}>Último backup completo: {summary?.lastBackupAt ? new Date(summary.lastBackupAt).toLocaleString('es-ES') : 'ninguno'}.</Text><Text selectable style={{ color: palette.muted }}>Escribe ELIMINAR. Después aparecerá una revisión accesible; si cancelas, no se inicia ninguna transacción.</Text><TextInput accessibilityLabel="Confirmación para eliminar todos mis datos" value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" style={input}/><ActionButton tone="danger" label="Eliminar todos mis datos" disabled={busy || confirmation !== 'ELIMINAR'} onPress={() => setEraseReviewOpen(true)}/></Card><AccessibleDialog confirmLabel="Eliminar filas del dataset activo" danger description={`Se eliminarán ${summary?.totalRows ?? 0} filas funcionales. Se conservarán nutriasta, el catálogo técnico, rollback, recuperación, backups en Archivos y la PWA.`} onCancel={() => { setEraseReviewOpen(false); setMessage('Eliminación cancelada. No se ha modificado ningún dato.'); }} onConfirm={() => void erase()} open={eraseReviewOpen} title="Última revisión antes de eliminar"/></View>;
}
function Notice({ text, danger = false }: { text: string; danger?: boolean }) { return <View style={{ backgroundColor: danger ? palette.dangerBackground : '#eaf5ff', borderRadius: 14, padding: 12 }}><Text selectable style={{ color: danger ? palette.danger : palette.navySoft, fontWeight: '700' }}>{text}</Text></View>; }
function messageFor(value: unknown) { return value instanceof Error ? value.message : 'Error inesperado.'; }
const input = { borderWidth: 1, borderColor: palette.border, borderRadius: 14, padding: 13, color: palette.ink, backgroundColor: '#f9fbfa', fontSize: 16 } as const;
