import { calculateFromSnapshot, sumNutrition } from '@/mvp/diary-calculations';
import type { DiaryDay, DiaryView, MealEntry, MealItem, MealState, MealType, NutritionSnapshot, QuantityUnit, TargetSnapshot, TrainingDayFlag, WaterEntry } from '@/mvp/diary-types';
import { mainDatabase, type NutrIAstaMainDatabase } from '@/storage/main-database.web';
import { MAIN_META_KEYS } from '@/storage/main-schema';
import { trackWrite } from '@/storage/write-tracker';
import { createId } from '@/utils/crypto';

export interface UpdateMealItemDraft { quantity: number; baseAmount: number; note: string; mealType: MealType; }

export class DiaryRepository {
  constructor(private readonly db: NutrIAstaMainDatabase = mainDatabase) {}
  private async datasetId() { await this.db.open(); const source = (await this.db.metadata.get(MAIN_META_KEYS.activeSource))?.value; const id = (await this.db.metadata.get(MAIN_META_KEYS.activeMainDatasetId))?.value; if (source !== 'main' || typeof id !== 'string') throw new Error('No existe un dataset principal activo.'); return id; }
  private async targetSnapshot(datasetId: string, date: string): Promise<TargetSnapshot> { const periods = await this.db.nutritionTargetPeriods.where('datasetId').equals(datasetId).toArray(); const target = periods.filter((value) => value.effectiveFrom <= date).sort((a, b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0]; return target ? { targetPeriodId: target.id, caloriesKcal: target.caloriesKcal, proteinG: target.proteinG, carbohydratesG: target.carbohydratesG, fatG: target.fatG, waterMl: target.waterMl } : { targetPeriodId: null, caloriesKcal: 0, proteinG: 0, carbohydratesG: 0, fatG: 0, waterMl: null }; }
  async ensureDay(date: string) { validateDate(date); const datasetId = await this.datasetId(); const existing = await this.db.diaryDays.get([datasetId, date]); if (existing) return existing; const now = new Date().toISOString(); const day: DiaryDay = { datasetId, date, targetSnapshot: await this.targetSnapshot(datasetId, date), createdAt: now, updatedAt: now }; await trackWrite(() => this.db.diaryDays.add(day)); return day; }
  async get(date: string): Promise<DiaryView> { const datasetId = await this.datasetId(); const day = await this.ensureDay(date); const entries = await this.db.mealEntries.where('[datasetId+date]').equals([datasetId, date]).toArray(); const meals = []; for (const entry of entries.sort((a, b) => (a.occurredAt ?? a.createdAt).localeCompare(b.occurredAt ?? b.createdAt))) { const items = await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId, entry.id]).toArray(); meals.push({ ...entry, items: items.sort((a, b) => a.createdAt.localeCompare(b.createdAt)), totals: sumNutrition(items.map((item) => item.calculated)) }); } const water = await this.db.waterEntries.where('[datasetId+date]').equals([datasetId, date]).toArray(); const training = (await this.db.trainingDayFlags.get([datasetId, date])) ?? null; return { day, meals, water, training, totals: sumNutrition(meals.filter((meal) => meal.state === 'consumed').map((meal) => meal.totals)), plannedTotals: sumNutrition(meals.filter((meal) => meal.state === 'planned').map((meal) => meal.totals)) }; }
  private async entry(datasetId: string, date: string, mealType: MealType, state: MealState, entryId?: string) { const now = new Date().toISOString(); if (entryId) { const existing = await this.db.mealEntries.get([datasetId, entryId]); if (!existing || existing.date !== date || existing.state !== state) throw new Error('La comida de destino no es válida para esta fecha y estado.'); return existing; } const value: MealEntry = { datasetId, id: createId('meal'), date, mealType, label: labelFor(mealType), state, occurredAt: now, createdAt: now, updatedAt: now }; return value; }
  async addFood(date: string, mealType: MealType, foodId: string, quantity: number, quantityUnit: QuantityUnit, baseAmount: number, note = '', state: MealState = 'consumed', entryId?: string, portionId?: string) {
    if (!Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(baseAmount) || baseAmount <= 0) throw new Error('La cantidad debe ser mayor que cero.');
    const datasetId = await this.datasetId(); await this.ensureDay(date); const food = await this.db.foods.get([datasetId, foodId]); if (!food || food.archived) throw new Error('El alimento no está disponible.');
    if (quantityUnit === 'g' && food.baseUnit !== 'g') throw new Error('Un alimento definido por 100 ml no puede registrarse en gramos sin densidad.');
    if (quantityUnit === 'ml' && food.baseUnit !== 'ml') throw new Error('Un alimento definido por 100 g no puede registrarse en mililitros sin densidad.');
    if ((quantityUnit === 'g' || quantityUnit === 'ml') && !nearlyEqual(baseAmount, quantity)) throw new Error('La cantidad directa debe coincidir con la unidad base del alimento.');
    if (quantityUnit === 'portion') { const portion = portionId ? await this.db.foodPortions.get([datasetId, portionId]) : undefined; if (!portion || portion.foodId !== food.id || portion.baseUnit !== food.baseUnit) throw new Error('Selecciona una porción guardada válida.'); if (!nearlyEqual(baseAmount, quantity * portion.amount)) throw new Error('La equivalencia de la porción no es correcta.'); }
    const now = new Date().toISOString(); const entry = await this.entry(datasetId, date, mealType, state, entryId); const isNewEntry = !entryId;
    const snapshot: NutritionSnapshot = { name: food.name, energyKcal: food.energyKcal, proteinG: food.proteinG, carbohydratesG: food.carbohydratesG, fatG: food.fatG, baseUnit: food.baseUnit, sourceUpdatedAt: food.updatedAt };
    const item: MealItem = { datasetId, id: createId('meal-item'), mealEntryId: entry.id, sourceType: 'food', sourceId: food.id, quantity, quantityUnit, baseAmount, portionId: quantityUnit === 'portion' ? portionId : undefined, nutritionSnapshot: snapshot, calculated: calculateFromSnapshot(snapshot, baseAmount), note: note.trim(), createdAt: now, updatedAt: now };
    await trackWrite(() => this.db.transaction('rw', this.db.mealEntries, this.db.mealItems, this.db.foods, async () => { if (isNewEntry) await this.db.mealEntries.add(entry); else await this.db.mealEntries.update([datasetId, entry.id], { updatedAt: now }); await this.db.mealItems.add(item); await this.db.foods.update([datasetId, food.id], { lastUsedAt: now }); })); return item;
  }
  async addRecipe(date: string, mealType: MealType, recipeId: string, quantity: number, quantityUnit: 'portion' | 'g', state: MealState = 'consumed', entryId?: string, note = '') { if (!Number.isFinite(quantity) || quantity <= 0) throw new Error('La cantidad debe ser mayor que cero.'); const datasetId = await this.datasetId(); await this.ensureDay(date); const recipe = await this.db.recipes.get([datasetId, recipeId]); if (!recipe || recipe.archived) throw new Error('La receta no está disponible.'); const ingredients = await this.db.recipeItems.where('[datasetId+recipeId]').equals([datasetId, recipeId]).toArray(); const totals = sumNutrition(ingredients.map((item) => item.calculated)); const factor = quantityUnit === 'portion' ? quantity / recipe.servings : recipe.finalWeightG ? quantity / recipe.finalWeightG : 0; if (factor <= 0) throw new Error('La receta necesita peso final para registrar gramos.'); const now = new Date().toISOString(); const entry = await this.entry(datasetId, date, mealType, state, entryId); const snapshot: NutritionSnapshot = { name: recipe.name, energyKcal: totals.energyKcal, proteinG: totals.proteinG, carbohydratesG: totals.carbohydratesG, fatG: totals.fatG, baseUnit: 'g', sourceUpdatedAt: recipe.updatedAt }; const calculated = { energyKcal: totals.energyKcal * factor, proteinG: totals.proteinG * factor, carbohydratesG: totals.carbohydratesG * factor, fatG: totals.fatG === null ? null : totals.fatG * factor }; const item: MealItem = { datasetId, id: createId('meal-item'), mealEntryId: entry.id, sourceType: 'recipe', sourceId: recipe.id, quantity, quantityUnit, baseAmount: quantityUnit === 'g' ? quantity : factor * 100, nutritionSnapshot: snapshot, calculated, note: note.trim(), createdAt: now, updatedAt: now }; await trackWrite(() => this.db.transaction('rw', this.db.mealEntries, this.db.mealItems, async () => { if (!entryId) await this.db.mealEntries.add(entry); else await this.db.mealEntries.update([datasetId, entry.id], { updatedAt: now }); await this.db.mealItems.add(item); })); return item; }
  async updateItem(id: string, draft: UpdateMealItemDraft) { if (!Number.isFinite(draft.quantity) || draft.quantity <= 0 || !Number.isFinite(draft.baseAmount) || draft.baseAmount <= 0) throw new Error('La cantidad debe ser mayor que cero.'); const datasetId = await this.datasetId(); const item = await this.db.mealItems.get([datasetId, id]); if (!item) throw new Error('El elemento no existe.'); const sourceEntry = await this.db.mealEntries.get([datasetId, item.mealEntryId]); if (!sourceEntry) throw new Error('La comida del elemento no existe.'); const now = new Date().toISOString(); await trackWrite(() => this.db.transaction('rw', this.db.mealItems, this.db.mealEntries, async () => { let targetId = sourceEntry.id; if (draft.mealType !== sourceEntry.mealType) { const target = await this.db.mealEntries.where('[datasetId+date]').equals([datasetId, sourceEntry.date]).filter((entry) => entry.mealType === draft.mealType && entry.state === sourceEntry.state).first(); if (target) targetId = target.id; else { targetId = createId('meal'); await this.db.mealEntries.add({ ...sourceEntry, id: targetId, mealType: draft.mealType, label: labelFor(draft.mealType), occurredAt: now, createdAt: now, updatedAt: now }); } } await this.db.mealItems.update([datasetId, id], { mealEntryId: targetId, quantity: draft.quantity, baseAmount: draft.baseAmount, note: draft.note.trim(), calculated: calculateFromSnapshot(item.nutritionSnapshot, draft.baseAmount), updatedAt: now }); await this.db.mealEntries.update([datasetId, targetId], { updatedAt: now }); if (targetId !== sourceEntry.id && await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId, sourceEntry.id]).count() === 0) await this.db.mealEntries.delete([datasetId, sourceEntry.id]); })); }
  async updateItemQuantity(id: string, quantity: number, baseAmount: number) { const datasetId = await this.datasetId(); const item = await this.db.mealItems.get([datasetId, id]); if (!item) throw new Error('El elemento no existe.'); const entry = await this.db.mealEntries.get([datasetId, item.mealEntryId]); if (!entry) throw new Error('La comida no existe.'); return this.updateItem(id, { quantity, baseAmount, note: item.note, mealType: entry.mealType }); }
  async convertMealToConsumed(entryId: string) { const datasetId = await this.datasetId(); await trackWrite(() => this.db.mealEntries.update([datasetId, entryId], { state: 'consumed', updatedAt: new Date().toISOString() })); }
  async copyMeal(entryId: string, targetDate: string, targetMealType?: MealType) { validateDate(targetDate); const datasetId = await this.datasetId(); await this.ensureDay(targetDate); const source = await this.db.mealEntries.get([datasetId, entryId]); if (!source) throw new Error('La comida no existe.'); const items = await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId, entryId]).toArray(); const now = new Date().toISOString(); const nextId = createId('meal'); const mealType = targetMealType ?? source.mealType; const copy: MealEntry = { ...source, id: nextId, date: targetDate, mealType, label: labelFor(mealType), state: targetDate > madridDate() ? 'planned' : source.state, occurredAt: now, createdAt: now, updatedAt: now }; await trackWrite(() => this.db.transaction('rw', this.db.mealEntries, this.db.mealItems, async () => { await this.db.mealEntries.add(copy); await this.db.mealItems.bulkAdd(items.map((item) => ({ ...item, id: createId('meal-item'), mealEntryId: nextId, createdAt: now, updatedAt: now }))); })); }
  async copyDay(sourceDate: string, targetDate: string) { const source = await this.get(sourceDate); for (const meal of source.meals) await this.copyMeal(meal.id, targetDate); }
  async recentMeals(limit = 5) { const datasetId = await this.datasetId(); const entries = (await this.db.mealEntries.where('datasetId').equals(datasetId).toArray()).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit); const result = []; for (const entry of entries) { const items = await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId, entry.id]).toArray(); result.push({ ...entry, items, totals: sumNutrition(items.map((item) => item.calculated)) }); } return result; }
  async recentSources(limit = 6) { const datasetId = await this.datasetId(); const items = (await this.db.mealItems.where('datasetId').equals(datasetId).toArray()).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); const seen = new Set<string>(); return items.filter((item) => { const key = `${item.sourceType}:${item.sourceId}`; if (seen.has(key)) return false; seen.add(key); return true; }).slice(0, limit); }
  async deleteItem(id: string) { const datasetId = await this.datasetId(); const item = await this.db.mealItems.get([datasetId, id]); if (!item) return; await trackWrite(() => this.db.transaction('rw', this.db.mealItems, this.db.mealEntries, async () => { await this.db.mealItems.delete([datasetId, id]); if (await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId, item.mealEntryId]).count() === 0) await this.db.mealEntries.delete([datasetId, item.mealEntryId]); })); }
  async addWater(date: string, amountMl: number) { if (!Number.isFinite(amountMl) || amountMl <= 0 || amountMl > 10000) throw new Error('La cantidad de agua no es válida.'); const datasetId = await this.datasetId(); await this.ensureDay(date); const now = new Date().toISOString(); const value: WaterEntry = { datasetId, id: createId('water'), date, amountMl, createdAt: now, updatedAt: now }; await trackWrite(() => this.db.waterEntries.add(value)); return value; }
  async updateWater(id: string, amountMl: number) { if (!Number.isFinite(amountMl) || amountMl <= 0 || amountMl > 10000) throw new Error('La cantidad de agua no es válida.'); const datasetId = await this.datasetId(); await trackWrite(() => this.db.waterEntries.update([datasetId, id], { amountMl, updatedAt: new Date().toISOString() })); }
  async deleteWater(id: string) { const datasetId = await this.datasetId(); await trackWrite(() => this.db.waterEntries.delete([datasetId, id])); }
  async setSteps(date: string, steps: number) { if (!Number.isInteger(steps) || steps < 0 || steps > 200_000) throw new Error('Los pasos del día deben ser un número entero entre 0 y 200.000.'); const datasetId = await this.datasetId(); await this.ensureDay(date); await trackWrite(() => this.db.diaryDays.update([datasetId, date], { steps, updatedAt: new Date().toISOString() })); return steps; }
  async saveTraining(date: string, trained: boolean, trainingType: string, note: string) { const datasetId = await this.datasetId(); await this.ensureDay(date); const value: TrainingDayFlag = { datasetId, date, trained, trainingType: trained ? trainingType.trim() : '', note: trained ? note.trim() : '', updatedAt: new Date().toISOString() }; await trackWrite(() => this.db.trainingDayFlags.put(value)); return value; }
}
function labelFor(type: MealType) { return { breakfast: 'Desayuno', lunch: 'Comida', dinner: 'Cena', snack: 'Tentempié' }[type]; }
function validateDate(date: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('La fecha no es válida.'); }
function nearlyEqual(left: number, right: number) { return Math.abs(left - right) < 0.000001; }
function madridDate() { return new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Madrid' }).format(new Date()); }
export const diaryRepository = new DiaryRepository();
