import { calculateFromSnapshot, sumNutrition, ZERO_TOTALS } from '@/mvp/diary-calculations';
import type { DiaryDay, DiaryView, MealEntry, MealItem, MealState, MealType, NutritionSnapshot, QuantityUnit, TargetSnapshot, TrainingDayFlag, WaterEntry } from '@/mvp/diary-types';
import { mainDatabase, type NutrIAstaMainDatabase } from '@/storage/main-database.web';
import { MAIN_META_KEYS } from '@/storage/main-schema';
import { trackWrite } from '@/storage/write-tracker';
import { createId } from '@/utils/crypto';

export class DiaryRepository {
  constructor(private readonly db: NutrIAstaMainDatabase = mainDatabase) {}
  private async datasetId() { await this.db.open(); const source=(await this.db.metadata.get(MAIN_META_KEYS.activeSource))?.value; const id=(await this.db.metadata.get(MAIN_META_KEYS.activeMainDatasetId))?.value; if(source!=='main'||typeof id!=='string')throw new Error('No existe un dataset principal activo.'); return id; }
  private async targetSnapshot(datasetId: string, date: string): Promise<TargetSnapshot> { const periods=await this.db.nutritionTargetPeriods.where('datasetId').equals(datasetId).toArray(); const target=periods.filter((value)=>value.effectiveFrom<=date).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]; return target ? { targetPeriodId:target.id, caloriesKcal:target.caloriesKcal, proteinG:target.proteinG, carbohydratesG:target.carbohydratesG, fatG:target.fatG, waterMl:target.waterMl } : { targetPeriodId:null, caloriesKcal:0, proteinG:0, carbohydratesG:0, fatG:0, waterMl:null }; }
  async ensureDay(date: string) { validateDate(date); const datasetId=await this.datasetId(); const existing=await this.db.diaryDays.get([datasetId,date]); if(existing)return existing; const now=new Date().toISOString(); const day:DiaryDay={datasetId,date,targetSnapshot:await this.targetSnapshot(datasetId,date),createdAt:now,updatedAt:now}; await trackWrite(()=>this.db.diaryDays.add(day)); return day; }
  async get(date: string): Promise<DiaryView> { const datasetId=await this.datasetId(); const day=await this.ensureDay(date); const entries=await this.db.mealEntries.where('[datasetId+date]').equals([datasetId,date]).toArray(); const meals=[]; for(const entry of entries.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))){const items=await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId,entry.id]).toArray(); meals.push({...entry,items,totals:sumNutrition(items.map((item)=>item.calculated))});} const water=await this.db.waterEntries.where('[datasetId+date]').equals([datasetId,date]).toArray(); const training=(await this.db.trainingDayFlags.get([datasetId,date]))??null; return {day,meals,water,training,totals:sumNutrition(meals.filter((meal)=>meal.state==='consumed').map((meal)=>meal.totals)),plannedTotals:sumNutrition(meals.filter((meal)=>meal.state==='planned').map((meal)=>meal.totals))}; }
  async addFood(date:string, mealType:MealType, foodId:string, quantity:number, quantityUnit:QuantityUnit, baseAmount:number, note='', state:MealState='consumed') { if(quantity<=0||baseAmount<=0)throw new Error('La cantidad debe ser mayor que cero.'); const datasetId=await this.datasetId(); await this.ensureDay(date); const food=await this.db.foods.get([datasetId,foodId]); if(!food||food.archived)throw new Error('El alimento no está disponible.'); const now=new Date().toISOString(); const entry:MealEntry={datasetId,id:createId('meal'),date,mealType,label:labelFor(mealType),state,createdAt:now,updatedAt:now}; const snapshot:NutritionSnapshot={name:food.name,energyKcal:food.energyKcal,proteinG:food.proteinG,carbohydratesG:food.carbohydratesG,fatG:food.fatG,baseUnit:food.baseUnit,sourceUpdatedAt:food.updatedAt}; const item:MealItem={datasetId,id:createId('meal-item'),mealEntryId:entry.id,sourceType:'food',sourceId:food.id,quantity,quantityUnit,baseAmount,nutritionSnapshot:snapshot,calculated:calculateFromSnapshot(snapshot,baseAmount),note,createdAt:now,updatedAt:now}; await trackWrite(()=>this.db.transaction('rw',this.db.mealEntries,this.db.mealItems,this.db.foods,async()=>{await this.db.mealEntries.add(entry);await this.db.mealItems.add(item);await this.db.foods.update([datasetId,food.id],{lastUsedAt:now});})); return item; }
  async addRecipe(date:string,mealType:MealType,recipeId:string,quantity:number,quantityUnit:'portion'|'g',state:MealState='consumed'){if(quantity<=0)throw new Error('La cantidad debe ser mayor que cero.');const datasetId=await this.datasetId();await this.ensureDay(date);const recipe=await this.db.recipes.get([datasetId,recipeId]);if(!recipe||recipe.archived)throw new Error('La receta no está disponible.');const ingredients=await this.db.recipeItems.where('[datasetId+recipeId]').equals([datasetId,recipeId]).toArray();const totals=sumNutrition(ingredients.map((item)=>item.calculated));const factor=quantityUnit==='portion'?quantity/recipe.servings:recipe.finalWeightG?quantity/recipe.finalWeightG:0;if(factor<=0)throw new Error('La receta necesita peso final para registrar gramos.');const now=new Date().toISOString();const entry:MealEntry={datasetId,id:createId('meal'),date,mealType,label:labelFor(mealType),state,createdAt:now,updatedAt:now};const snapshot:NutritionSnapshot={name:recipe.name,energyKcal:totals.energyKcal,proteinG:totals.proteinG,carbohydratesG:totals.carbohydratesG,fatG:totals.fatG,baseUnit:'g',sourceUpdatedAt:recipe.updatedAt};const calculated={energyKcal:totals.energyKcal*factor,proteinG:totals.proteinG*factor,carbohydratesG:totals.carbohydratesG*factor,fatG:totals.fatG*factor};const item:MealItem={datasetId,id:createId('meal-item'),mealEntryId:entry.id,sourceType:'recipe',sourceId:recipe.id,quantity,quantityUnit:quantityUnit==='portion'?'portion':'g',baseAmount:quantityUnit==='g'?quantity:factor*100,nutritionSnapshot:snapshot,calculated,note:'',createdAt:now,updatedAt:now};await trackWrite(()=>this.db.transaction('rw',this.db.mealEntries,this.db.mealItems,async()=>{await this.db.mealEntries.add(entry);await this.db.mealItems.add(item);}));return item;}
  async convertMealToConsumed(entryId:string){const datasetId=await this.datasetId();await trackWrite(()=>this.db.mealEntries.update([datasetId,entryId],{state:'consumed',updatedAt:new Date().toISOString()}));}
  async copyMeal(entryId:string,targetDate:string){validateDate(targetDate);const datasetId=await this.datasetId();await this.ensureDay(targetDate);const source=await this.db.mealEntries.get([datasetId,entryId]);if(!source)throw new Error('La comida no existe.');const items=await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId,entryId]).toArray();const now=new Date().toISOString();const nextId=createId('meal');const copy:MealEntry={...source,id:nextId,date:targetDate,state:targetDate>new Date().toISOString().slice(0,10)?'planned':source.state,createdAt:now,updatedAt:now};await trackWrite(()=>this.db.transaction('rw',this.db.mealEntries,this.db.mealItems,async()=>{await this.db.mealEntries.add(copy);await this.db.mealItems.bulkAdd(items.map((item)=>({...item,id:createId('meal-item'),mealEntryId:nextId,createdAt:now,updatedAt:now})));}));}
  async copyDay(sourceDate:string,targetDate:string){const source=await this.get(sourceDate);for(const meal of source.meals)await this.copyMeal(meal.id,targetDate);}
  async updateItemQuantity(id:string, quantity:number, baseAmount:number){if(quantity<=0||baseAmount<=0)throw new Error('La cantidad debe ser mayor que cero.');const datasetId=await this.datasetId();const item=await this.db.mealItems.get([datasetId,id]);if(!item)throw new Error('El elemento no existe.');await trackWrite(()=>this.db.mealItems.update([datasetId,id],{quantity,baseAmount,calculated:calculateFromSnapshot(item.nutritionSnapshot,baseAmount),updatedAt:new Date().toISOString()}));}
  async deleteItem(id:string){const datasetId=await this.datasetId();const item=await this.db.mealItems.get([datasetId,id]);if(!item)return;await trackWrite(()=>this.db.transaction('rw',this.db.mealItems,this.db.mealEntries,async()=>{await this.db.mealItems.delete([datasetId,id]);if(await this.db.mealItems.where('[datasetId+mealEntryId]').equals([datasetId,item.mealEntryId]).count()===0)await this.db.mealEntries.delete([datasetId,item.mealEntryId]);}));}
  async addWater(date:string,amountMl:number){if(!Number.isFinite(amountMl)||amountMl<=0||amountMl>10000)throw new Error('La cantidad de agua no es válida.');const datasetId=await this.datasetId();await this.ensureDay(date);const now=new Date().toISOString();const value:WaterEntry={datasetId,id:createId('water'),date,amountMl,createdAt:now,updatedAt:now};await trackWrite(()=>this.db.waterEntries.add(value));return value;}
  async updateWater(id:string,amountMl:number){if(amountMl<=0)throw new Error('La cantidad de agua no es válida.');const datasetId=await this.datasetId();await trackWrite(()=>this.db.waterEntries.update([datasetId,id],{amountMl,updatedAt:new Date().toISOString()}));}
  async deleteWater(id:string){const datasetId=await this.datasetId();await trackWrite(()=>this.db.waterEntries.delete([datasetId,id]));}
  async saveTraining(date:string,trained:boolean,trainingType:string,note:string){const datasetId=await this.datasetId();await this.ensureDay(date);const value:TrainingDayFlag={datasetId,date,trained,trainingType:trained?trainingType.trim():'',note:trained?note.trim():'',updatedAt:new Date().toISOString()};await trackWrite(()=>this.db.trainingDayFlags.put(value));return value;}
}
function labelFor(type:MealType){return {breakfast:'Desayuno',lunch:'Comida',dinner:'Cena',snack:'Tentempié'}[type];}
function validateDate(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('La fecha no es válida.');}
export const diaryRepository=new DiaryRepository();
